services:
  express-app:
    image: docker.io/iku1/express-app:latest
    container_name: express-app
    ports:
      - "8080:8080"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60 express-app
